---
title: "Air Pollution"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
    theme: spacelab
---
*Dashboard developed by Kiran using the Plotly R package*

```{r setup, include=FALSE}
library(tidyverse)
library(dplyr)
library(rnoaa)
library(ggplot2)
library(plotly)

```

```{r, include=FALSE}

ma_pm2_5 = read_csv("./data/ma_pm2_5.csv") %>% 
  janitor::clean_names() %>% 
  drop_na(local_site_name) %>% 
  mutate(date = as.Date(date, format = "%m/%d/%Y")) %>% 
    rename(pm_2_5_ugm3_daily = daily_mean_pm2_5_concentration,
           latitude = site_latitude,
           longitude = site_longitude) 

ma_pm2_5_summary = ma_pm2_5 %>% 
    filter(date >= "2023-07-01" & date <= "2023-08-31") %>% 
      group_by(site_id, local_site_name, latitude, longitude) %>% 
      summarize(avg_pm2_5 = mean(pm_2_5_ugm3_daily))
  

```


```{r, include=FALSE}
ma_pm2_5_summary |>
  mutate(text_label = str_c("PM2.5 Average= ", avg_pm2_5, "ug/m3", "\nSite: ", local_site_name)) |> 
  plot_ly(
    x = ~latitude, y = ~longitude, type = "scatter", mode = "markers",
    color = ~avg_pm2_5, text = ~text_label, alpha = 1.0)
```


```{r, include=FALSE}
# Create text label
ma_pm2_5_summary <- ma_pm2_5_summary %>%
  mutate(text_label = str_c(
    "PM2.5 Average = ", round(avg_pm2_5, 2), " µg/m³", "\nSite: ", local_site_name))

# Plotly plot
air_plot <- 
  plot_ly(
  data = ma_pm2_5_summary,
  x = ~latitude, y = ~longitude,
  type = "scatter", mode = "markers",
  color = ~avg_pm2_5,
  text = ~text_label,
  alpha = 1.0,
  marker = list(
    size = ~avg_pm2_5*2,  # Adjust size multiplier as needed
    opacity = 60  # Adjust opacity if needed
  )) %>%
layout(
  title = "Average PM2.5 (µg/m³) across Sites in MA in July-Aug 2023",  # Title of the plot
  xaxis = list(title = "Latitude"),  # X-axis label
  yaxis = list(title = "Longitude"),  # Y-axis label
  colorbar = list(
    title = list(text = "Average PM2.5 (µg/m³) across Sites in MA in July-Aug 2023", side = "right"),
    tickformat = ".2f"  # Format ticks as 2 decimal places
  )
)

```

```{r}

air_plot

```

*data from EPA*

