---
title: "Project: COVID-19 Maps"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
    theme: spacelab
---
*Maps developed by Kiran using the tidycensus, sf and tmap packages, data from US Census*

```{r setup, include=FALSE, message=FALSE}
library(sf)
library(tmap)
library(tidyverse)
library(rgeoda)
library(biscale)
library(cowplot)
library(RColorBrewer)
library(reticulate)
```

```{r, include=FALSE, warning=FALSE, message=FALSE}
# Read-in shp
covid_zip <- st_read("/Users/kuiyan/Desktop/R Projects/kirankui.github.io/data/NYC_covid19_zip.shp")

```

### Poverty and COVID-19 Deaths in NYC from 2020 to 2021
```{r, echo=FALSE, warning=FALSE, message=FALSE}
tm_shape(covid_zip) +
  tm_polygons(col =  "per_pov",
              style = "quantile",
              n = 4,
              title = "Percent Poor",
              palette = "Purples",
              border.col = "black") +
  tm_shape(covid_zip) +
  tm_dots(col = "black",
          size = "r_death",
          style = "quantile",
          title = c("Death Rate"),
          palette = "Purples",
          border.col = "black")

```

```{r, include=FALSE, warning=FALSE, message=FALSE}
deaths <- st_read("/Users/kuiyan/Desktop/R Projects/kirankui.github.io/data/NYC_covid19_zip.shp")

clusters <-  st_read("/Users/kuiyan/Desktop/R Projects/kirankui.github.io/data/clusters_death.shp")

sites <- st_read("/Users/kuiyan/Desktop/R Projects/kirankui.github.io/data/NYC_covid19_vacc_sites.shp")

deaths = deaths %>% 
  rename("percent_over_65_yo" = per_pop65,
         "percent_high_school" = per_highed,
         "percent_poverty" = per_pov,
         "percent_income" = per_pubinc,
         "infection" =  r_covid) 
  
```

### Interactive Map showing COVID-19 Deaths in NYC from 2020 to 2021

*Click to view sociodemographics*
```{r, echo=FALSE, warning=FALSE, message=FALSE}
tmap_mode("view")

tm_shape(deaths) +
  tm_polygons(col = "r_death",
              palette = "GnBu",
              alpha = .8,
              style = "quantile",
              n = 4,
              border.col = "white",
              lwd = .5,
              title = "Death Rate",
              interactive = TRUE,
              popup.vars = c("percent_over_65_yo",  "percent_high_school", "percent_poverty", "infection"))

```

