---
title: "Heat Stress"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
    theme: spacelab
---
*Dashboard developed by Kiran using the Plotly R package, data from NOAA*

```{r setup, include=FALSE}
library(tidyverse)
library(dplyr)
library(rnoaa)
library(ggplot2)
library(plotly)

```

### Boxplot showing Ambient Temperature across Time

```{r, include=FALSE}
# Get a list of all NY station IDs
nyc_noaa_df <-read_csv("/Users/kuiyan/Desktop/R Projects/kirankui.github.io/data/nynoaadat.csv")

nyc_noaa_df = nyc_noaa_df %>% 
  dplyr::select(id, date, tmax, tmin, everything()) %>% 
  filter(date >= as.Date("2010-07-01") & date <= as.Date("2010-08-31")) %>% 
  drop_na(id, date, tmax, tmin) %>% 
  mutate(tmax_c = tmax/10,
         tmax_f = tmax_c*1.8 + 32,
         tmin_c = tmin/10,
         tmin_f = tmin_c*1.8 + 32,
         prcp = prcp/10)

```


```{r, echo=FALSE}
box_ggplot = 
  nyc_noaa_df |> 
  ggplot(aes(x = date, y = tmax_f, fill = factor(date))) +
  geom_boxplot() +
   labs(
    title = "Daily Maximum Temperature Distribution across NY in July-Aug 2010",
    x = "Date",
    y = "Maximum Temperature (°F)",
    fill = "Date"
  ) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

```

```{r, echo=FALSE, warning=FALSE}

ggplotly(box_ggplot)

```

### Time Series Plot showing Temperature and Precipitation

```{r, echo=FALSE, warning=FALSE}

# central park weather station
central_park_df = nyc_noaa_df %>% 
  filter(id == "USW00094728")

central_park_temp <- plot_ly(central_park_df, 
                             x = ~date, 
                             y = ~tmin_f, 
                             name = 'Daily Minimum Temperature (°F)', 
                             type = 'scatter', 
                             mode = 'lines+markers') %>%
  layout(
    title = 'Daily Temperature and Precipitation at Central Park in July-Aug 2010',
    yaxis = list(title = 'Temperature (°F)'),
    xaxis = list(title = 'Date'),
    legend = list(
      orientation = 'h',
      y = -0.3,
      x = 0.5,
      xanchor = 'center',
      yanchor = 'bottom'
    )
  )

central_park_temp = central_park_temp %>% 
  add_trace(y = ~tmax_f, 
            name = 'Daily Maximum Temperature (°F)', 
            mode = 'lines+markers')

central_park_temp = central_park_temp %>% 
  add_trace(y = ~prcp, 
            name = 'Precipitation (mm)', 
            mode = 'lines+markers')

central_park_temp

```



